### ISSUE TITLE
Error in 3.1.0 with `Intl.PluralRules.supportedLocalesOf`

### ISSUE THREAD

**Issue by tmeasday** [chromaui/chromatic-cli#76]
```
Uncaught [TypeError: Intl.PluralRules.supportedLocalesOf is not a function]
```

The issue did not occur in 3.0.3, and seems likely to have been caused by https://github.com/chromaui/chromatic-cli/pull/53

**Comment by tmeasday** [comment]
LGTM on staging
