### ISSUE TITLE
Module Error when updating from 6.11 to 6.13

### ISSUE THREAD

**Issue by mdbatruch** [chromaui/chromatic-cli#701]
**Bug report**

Coming across an issue when updating the Chromatic Library from v6.11.4 to v6.13.1:

`Error: cannot find module 'node:http'`

Unsure what the issue is stemming from and not sure why module `node:http` is missing now. 
Last working version was `v6.11.4`, but error appears also on `v6.12` and `v6.13`. Has been happening when we are running the chromatic upload command.

![Screen Shot 2022-12-19 at 9 21 47 AM](https://user-images.githubusercontent.com/22670002/208449117-9c6c87e5-5b10-41bf-89ad-0b31df4822e7.png)

**Comment by codykaup** [comment]
Hey @mdbatruch! 👋 

Sorry for the troubles here! There was a recent dependency upgrade that broke some older Node versions. We're working on a check to point this out but you should just have to upgrade to Node v14.18+ and it should work for ya!

**Comment by mdbatruch** [comment]
> Hey @mdbatruch! 👋
> 
> Sorry for the troubles here! There was a recent dependency upgrade that broke some older Node versions. We're working on a check to point this out but you should just have to upgrade to Node v14.18+ and it should work for ya!

Thanks @codykaup will take a look and let you know if anything!

**Comment by thafryer** [comment]
Hi @mdbatruch! We've released a few new versions since this issue that you can update to. I'll be closing this for now. Please don't hesitate to let me know if you run into any more problems.

**Comment by MWhiteFearless** [comment]
Hi, I'm running in to this same issue using chromatic 6.17.3 (also saw it on 6.17.2) and node v14.17.6. I upgraded from chromatic v6.5.3 recently when upgrading storybook to 6.5.16. For me the error happens when trying to run chromatic

**Comment by cejaramillof** [comment]
> Hi, I'm running in to this same issue using chromatic `6.17.3` (also saw it on 6.17.2) and node `v14.17.6`. I upgraded from chromatic v6.5.3 recently when upgrading storybook to 6.5.16. For me the error happens when trying to run chromatic

I just had the same issue, and it was solved by upgrading node version to 14.21.3
